// <auto-generated />
namespace StaffTrainee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatecoursetbale : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecoursetbale));

        string IMigrationMetadata.Id
        {
            get { return "202106110415515_updatecoursetbale"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
