// <auto-generated />
namespace StaffTrainee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deleteunique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteunique));
        
        string IMigrationMetadata.Id
        {
            get { return "202106141401107_deleteunique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
